sudo: required
dist: trusty
jdk: oraclejdk8

language: node_js

matrix:
  include:
    - node_js: "stable"
      env: TEST_BROWSER=0
    - node_js: "stable"
      env: TEST_BROWSER=1

cache:
  directories:
    - node_modules
    - vendor/java_home

install:
  - npm install
  - ./node_modules/.bin/tsc --version
  - ./node_modules/.bin/grunt --version

addons:
  firefox: "latest"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get install haveged
  - sudo service haveged start

script:
  - if test $TEST_BROWSER -eq 0; then echo "grunt test"; ./node_modules/.bin/grunt test --grunt-ignore-compile-errors; else echo "grunt test-browser-travis"; ./node_modules/.bin/grunt test-browser-travis --grunt-ignore-compile-errors; fi
